[package]
name = "tx_state_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
scylla = "0.14.0"
thiserror = "1.0.64"
tokio = "1.40.0"
uuid = "1.10.0"

