[package]
name = "flatbuf"
version = "0.1.0"
edition = "2021"

[build-dependencies]
flatc-rust = "*"

[dependencies]
flatbuffers = "24.3.25"

[lints.rust]
# The generated flatbuffers code triggers a bunch of benign and unactionable compiler warnings.
warnings = "allow"
