apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chardonnay-epoch-publisher
  namespace: chardonnay
spec:
  serviceName: "chardonnay-epoch-publisher"
  replicas: 1
  selector:
    matchLabels:
      app: chardonnay-epoch-publisher
  template:
    metadata:
      labels:
        app: chardonnay-epoch-publisher
    spec:
      containers:
      - name: epoch-publisher
        image: chardonnay-epoch-publisher:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: backend
          protocol: TCP
        - containerPort: 50052
          name: fast-network
          protocol: UDP
        env:
        - name: RUST_LOG
          value: "info"
        workingDir: /etc/chardonnay
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/chardonnay/config.json && epoch_publisher"]
        volumeMounts:
        - name: config
          mountPath: /etc/chardonnay
      volumes:
      - name: config
        configMap:
          name: chardonnay-epoch-publisher-config

---
apiVersion: v1
kind: Service
metadata:
  name: chardonnay-epoch-publisher
  namespace: chardonnay
spec:
  selector:
    app: chardonnay-epoch-publisher
  clusterIP: None
  ports:
    - name: backend
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: fast-network
      protocol: UDP
      port: 50052
      targetPort: 50052

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chardonnay-epoch-publisher-config
  namespace: chardonnay
data:
  config.json: |
    {
        "range_server": {
            "range_maintenance_duration": {
                "secs": 1,
                "nanos": 0
            },
            "proto_server_addr": "0.0.0.0:50054",
            "fast_network_addr": "0.0.0.0:50055"
        },
        "epoch": {
            "proto_server_addr": "chardonnay-epoch:50050"
        },
        "cassandra": {
            "cql_addr": "cassandra:9042"
        },
        "regions": {
            "test-region": {
                "warden_address": "chardonnay-warden:50053",
                "epoch_publishers": [
                    {
                        "name": "ps1",
                        "zone": "test-region/a",
                        "publishers": [
                            {
                                "name": "ep1",
                                "backend_addr": "0.0.0.0:50051",
                                "fast_network_addr": "0.0.0.0:50052"
                            }
                        ]
                    }
                ]
            }
        }
    }
