---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chardonnay-universe
  namespace: chardonnay
  labels:
    app: chardonnay-universe
spec:
  serviceName: chardonnay-universe
  replicas: 1
  selector:
    matchLabels:
      app: chardonnay-universe
  template:
    metadata:
      labels:
        app: chardonnay-universe
    spec:
      containers:
      - name: universe
        image: chardonnay-universe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50056
        workingDir: /etc/chardonnay
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/chardonnay/config.json && universe"]
        volumeMounts:
        - name: config
          mountPath: /etc/chardonnay
      volumes:
      - name: config
        configMap:
          name: chardonnay-universe-config
---
apiVersion: v1
kind: Service
metadata:
  name: chardonnay-universe
  namespace: chardonnay
  labels:
    app: chardonnay-universe
spec:
  ports:
  - port: 50056
    name: grpc
  clusterIP: None
  selector:
    app: chardonnay-universe

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chardonnay-universe-config
  namespace: chardonnay
data:
  config.json: |
    {
      "range_server": {
          "range_maintenance_duration": {
              "secs": 1,
              "nanos": 0
          },
          "proto_server_addr": "0.0.0.0:50054",
          "fast_network_addr": "0.0.0.0:50055"
        },
        "universe": {
            "proto_server_addr": "0.0.0.0:50056"
        },
        "epoch": {
            "proto_server_addr": "chardonnay-epoch:50050"
        },
        "cassandra": {
            "cql_addr": "cassandra:9042"
        },
        "regions": {
            "test-region": {
                "warden_address": "chardonnay-warden:50053",
                "epoch_publishers": [
                    {
                        "name": "ps1",
                        "zone": "test-region/a",
                        "publishers": [
                            {
                                "name": "ep1",
                                "backend_addr": "chardonnay-epoch-publisher:50051",
                                "fast_network_addr": "chardonnay-epoch-publisher:50052"
                            }
                        ]
                    }
                ]
            }
        }
    }