name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code

    # TODO: Might need to wait a bit until Cassandra becomes ready.
    - name: Set up Docker Container
      run: docker run -d -p 9042:9042 --name cassandra cassandra:5.0

    - name: Install flatbuffers
      run: scripts/linux_install_flatbuffers.sh

    - name: Install protobuf
      run: sudo apt install -y protobuf-compiler

    - name: Install cqlsh
      run: pip install cqlsh

    - name: Build
      run: cargo build

    - name: Create keyspace
      run: |
        cqlsh -f schema/cassandra/chardonnay/keyspace.cql
        cqlsh -k chardonnay -f schema/cassandra/chardonnay/schema.cql

    - name: Run tests
      run: cargo test

  build-docker-images:
    runs-on: ubuntu-latest
    # docker build -t $RANGESERVER_IMG --target rangeserver .
    # docker build -t $WARDEN_IMG --target warden .
    # docker build -t $EPOCH_PUBLISHER_IMG --target epoch_publisher .
    # docker build -t $EPOCH_IMG --target epoch .
    # docker build -t $UNIVERSE_IMG --target epoch .
    strategy:
      matrix:
        include:
          - target: rangeserver
            tags: chardonnay-rangeserver:latest
          - target: warden
            tags: chardonnay-warden:latest
          - target: epoch_publisher
            tags: epoch-publisher:latest
          - target: epoch
            tags: epoch:latest
          - target: universe
            tags: universe:latest

    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        target: ${{ matrix.target }}
        tags: ${{ matrix.tags }}
        push: false

  # TODO: Add an action to test deploying Chardonnay on a minikube cluster